export { Code } from './code'
export { H1, H2, H3, H4, H5, H6 } from './headers'
export { SectionHeader } from './sectionHeader'
export { Text } from './text'
export type { TextShorthandProps } from './textShorthands'
export { mergeTextShorthands } from './textShorthands'